name: Build LineageOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib \
            git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
            lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev \
            libssl-dev libxml2 libxml2-utils lzop pngcrush rsync \
            schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-17-jdk

    - name: Initialize repo
      run: |
        mkdir lineage && cd lineage
        repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
        repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)

    - name: Build ROM
      run: |
        cd lineage
        source build/envsetup.sh
        lunch lineage_yourdevice-userdebug
        make bacon -j$(nproc --all)

    - name: Upload ROM
      uses: actions/upload-artifact@v4
      with:
        name: LineageOS-ROM
        path: lineage/out/target/product/*/*.zip
