name: LXDE Desktop via noVNC + Cloudflare

on: workflow_dispatch

jobs:
  desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Install LXDE and noVNC
        run: |
          sudo apt update
          sudo apt install -y lxde-core lxterminal tightvncserver novnc websockify wget
          mkdir -p ~/.vnc
          echo "password" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Start VNC server
        run: |
          export DISPLAY=:1
          vncserver :1 -geometry 1280x720 -depth 24
          # Run websockify (noVNC bridge)
          websockify --web=/usr/share/novnc/ 6080 localhost:5901 &

      - name: Download Cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Cloudflared tunnel
        run: |
          cloudflared tunnel --url http://localhost:6080 --no-autoupdate &
          sleep 5

      - name: Keep job alive
        run: |
          echo "✅ LXDE Desktop is running!"
          echo "➡️ Open the Cloudflare URL printed above to access it."
          echo "🛑 Stop the workflow manually when done."
          python3 -c "import time; print('Keeping session alive...'); time.sleep(36000)"
